site_name: Arm on AWS
site_description: 'Using Arm on AWS'
site_author: 'Michael Hausenblas'
copyright: 'Copyright &copy; 2019 Amazon'
docs_dir: docs/
repo_name: 'mhausenblas/arm.aws-cloud.dev'
repo_url: 'https://github.com/mhausenblas/arm.aws-cloud.dev'
nav:
    - Home: index.md
    - Tools: tools.md
theme:
    name: 'material'
    palette:
      primary: 'blue grey'
      accent: 'orange'
    highlightjs: true
    hljs_languages:
        - yaml
        - json
        - bash
markdown_extensions:
    - toc:
        permalink: true
    - admonition
    - codehilite:
        linenums: true
